---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "MacroWorks - 매크로 웍스 웹 자동화"
keywords:    "웹 자동화, 매크로, 홍보기, 디시인사이드 홍보기, 네이버 카페 글 등록기, 다음 카페 글 등록기, 페이스북 자동화, 인스타그램 자동화, 트위터 자동화"
description: "웹 자동화 기술을 개발하는 매크로 웍스팀 홈페이지"
source_link: "https://github.com/macroworks/macroworks.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-139411298-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

